### PR TITLE
[WIP] Crud for Decks

### PR DESCRIPTION
**Pull request by vvscode**

### CODE REVIEW

**Comment by vvscode** [comment]
And one more question -- right now all options content wrapped into `form` -- so options page reload on every button press. Suppose the idea was - handle use interaction and reload page to redraw all content. Right?

**Comment by luzhanov** [comment]
> right now all options content wrapped into form -- so options page reload on every button press. Suppose the idea was - handle use interaction and reload page to redraw all content. Right?

It comes from the first author of plugin before I start to update it. So feel free to optimize it.

**Comment by luzhanov** [comment]
I really like your solution with DeckMng! 
Definitely we need something like this for other stored information.

**Comment by vvscode** [comment]
It's not ready )))

Some question
1) should we allow identical names for decks? ( if yes - I'll add deckId  field )
2) There are 2 functions to load decks into list. One of them support nested decks (??) -- it should work with ankiweb decks? do we need both?

**Comment by luzhanov** [comment]
> should we allow identical names for decks? ( if yes - I'll add deckId field )

No, It's confusing

> There are 2 functions to load decks into list. One of them support nested decks (??) -- it should work with ankiweb decks? do we need both?

Nested decks comes from the Anki API and now we can skip them - it will simplify logic. So, for now we will have only flat list, without "subdecks".

**Pull request merged**
